FROM node:alpine as build-deps

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json .

COPY yarn.lock .

COPY . .

RUN yarn 

RUN yarn run build

FROM nginx:1.19.5-alpine

RUN rm /etc/nginx/nginx.conf

COPY --from=build-deps ./usr/src/app/nginx.conf /etc/nginx/nginx.conf

COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g" ,"daemon off;" ]

