FROM node:15.3.0-alpine3.10

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN yarn global add pm2

COPY package*.json .

COPY yarn.lock .

COPY . .

RUN yarn 

RUN yarn run build

EXPOSE 3000

USER node

CMD ["pm2-runtime", "npm" ,"--","start"] 