version: "3.8"

services:
  negfront:
    restart: always
    container_name: negfront
    build:
      context: ./front-negocios
      dockerfile: Dockerfile.prod
     
    ports:
      - "4000:80"
    links: 
      - "negback"
      - "negsignup"
      - "negupimage"

  negback:
    restart: always
    container_name: negback
    build:
      context: ./back-negocios
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    

  negsignup:
    restart: always
    container_name: negsignup
    image: raulzarza/signupservice
    env_file:
      - prod.env

  negupimage:
    restart: always
    container_name: negupimage
    image: raulzarza/uploadimage:latest
    env_file:
      - prod.env

