version: "3.8"

services:
  front:
    build:
      context: ./front-negocios
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-dev-net
    volumes:
      - "./front-negocios:/app"
      - "/app/node_modules"

  back:
    build:
      context: ./back-negocios
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my-dev-net
    env_file:
      - .env
    volumes:
      - ./back-negocios:/usr/src/app

  uploadimage:
    image: raulzarza/uploadimage:latest
    ports:
      - 4042:4042
    networks:
      - my-dev-net
    env_file:
      - .env

  signupservice:
    image: raulzarza/signupservice
    ports:
      - 3015:3015
    networks:
      - my-dev-net
    env_file:
      - .env

networks:
  my-dev-net:
    driver: bridge
