version: "3.8"

services:
  
  front:
    restart: always
    build:
      context: ./front-negocios
      dockerfile: Dockerfile.prod
    ports:
      - "4000:80"
  
    networks:
      - negocios-net

  back:
    restart: always
    build:
      context: ./back-negocios
      dockerfile: Dockerfile.prod
    ports:
      - "4001:4001"
    networks:
      - negocios-net
    env_file: 
      - prod.env

  uploadimage:
    restart: always
    ports:
      - 4042:4042
    networks:
      - negocios-net
    env_file: 
      - prod.env

  signupservice:
    restart: always
    ports:
      - 3015:3015
    networks:
      - negocios-net
    networks:
      - negocios-net
    env_file: 
      - prod.env

networks:
  negocios-net:
    driver: bridge
