version: "3.8"

services:
  front:
    build:
      context: ./front-negocios
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-dev-net
    volumes:
      - "./front-negocios:/app"
      - "/app/node_modules"
    environment: 
      - REACT_APP_SIGNUP_SERVICE
      - REACT_APP_ADVERTS
      - REACT_APP_UPLOADIMAGE_SERVICE

  back:
    build:
      context: ./back-negocios
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - my-dev-net
    environment:
      - PORT
      - ENVIROMENT
      - MONGO_NDB
      - JWT_SECRET_TEXT
      - EMAIL_PASSWORD
      - NDB_EMAIL
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET

    volumes:
      - ./back-negocios:/usr/src/app

  uploadimage:
    image: raulzarza/uploadimage:latest
    ports:
      - 4042:4042
    networks:
      - my-dev-net
    environment:
      - ENVIROMENT
      - MONGODB_URI
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - UPLOAD_IMAGE_PORT
  
  signupservice:
    image: raulzarza/signupservice
    ports:
      - 3015:3015
    networks: 
      - my-dev-net
    environment: 
      - USERS_SERVICE_DB
      - FRONT_HOST
      - JWT_SECRET_TEXT
      - SIGNUP_PORT
      - EMAIL_PASSWORD
      - EMAIL_USER
  
      
  

networks:
  my-dev-net:
    driver: bridge
