version: "3.8"

services:
  client:
    build:
      context: ./front-negocios
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    networks:
      - my-dev-net
  api:
    build:
      context: ./back-negocios
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    networks:
      - my-dev-net
    environment:
      - PORT
      - MONGO_NDB
      - JWT_SECRET_TEXT
      - EMAIL_PASSWORD
      - NDB_EMAIL
      - ENVIROMENT
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
networks:
  my-dev-net:
    driver: bridge
