version: "3.8"

services:
  front:
    restart: always
    container_name: negfront
    build:
      context: ./front-negocios
      dockerfile: Dockerfile.prod
    ports:
      - "4000:80"
    networks:
      - negocios

  negback:
    restart: always
    container_name: negback
    build:
      context: ./back-negocios
      dockerfile: Dockerfile.prod
    ports:
      - 3001:4001
    networks:
      - negocios
    env_file:
      - .env

  uploadimage:
    restart: always
    container_name: negupimage
    image: raulzarza/uploadimage:latest
    ports:
      - 4042:4003
    networks:
      - negocios
    env_file:
      - .env

  signupservice:
    restart: always
    container_name: negsignup
    image: raulzarza/signupservice
    ports:
      - 3015:4002
    networks:
      - negocios
    env_file:
      - .env

networks:
  negocios:
    driver: bridge
