export const ESTADOS_MX = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Coahila de Zaragoza",
  "Colima",
  "Chiapas",
  "Chihuahua",
  "CDMX",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Estado de Mexico",
  "Michoacán de Ocampo",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz ",
  "Yucatán",
  "Zacatecas",
];

export const ESTADOS_LABEL_MX = [
  { label: "Aguascalientes", value: "AGU" },
  { label: "Baja California", value: "BCN" },
  { label: "Baja California Sur", value: "BCS" },
  { label: "Campeche", value: "CAM" },
  { label: "Coahila de Zaragoza", value: "CHP" },
  { label: "Colima", value: "CHH" },
  { label: "Chiapas", value: "CMX3​" },
  { label: "Chihuahua", value: "COA" },
  { label: "CDMX", value: "COL" },
  { label: "Durango", value: "DUR" },
  { label: "Guanajuato", value: "GUA" },
  { label: "Guerrero", value: "GRO" },
  { label: "Hidalgo", value: "HID" },
  { label: "Jalisco", value: "JAL" },
  { label: "Estado de Mexico", value: "MEX" },
  { label: "Michoacán de Ocampo", value: "MIC" },
  { label: "Morelos", value: "MOR" },
  { label: "Nayarit", value: "NAY" },
  { label: "Nuevo León", value: "NLE" },
  { label: "Oaxaca", value: "OAX" },
  { label: "Puebla", value: "PUE" },
  { label: "Querétaro", value: "QUE" },
  { label: "Quintana Roo", value: "ROO" },
  { label: "San Luis Potosí", value: "SLP" },
  { label: "Sinaloa", value: "SIN" },
  { label: "Sonora", value: "SON" },
  { label: "Tabasco", value: "TAB" },
  { label: "Tamaulipas", value: "TAM" },
  { label: "Tlaxcala", value: "TLA" },
  { label: "Veracruz ", value: "VER" },
  { label: "Yucatán", value: "YUC" },
  { label: "Zacatecas", value: "ZAC" },
];
